[package]
name = "fuso"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
panic = 'abort'
debug = false

[workspace]
members = [
    "./fuso-api",
    "./fuso-core",
    "./fuso-socks"
]

[[bin]]
name = "fus"
path = "src/server.rs"

[[bin]]
name = "fuc"
path = "src/client.rs"


[dependencies]
log = {version = "0.4.14"}
clap = {version = "3.0.0-beta.5", features = ["yaml"]}
smol = {version = "1.2.5"}
bytes = {version = "1.1.0"}
futures = "0.3"
env_logger = "0.9.0"
fuso-core = {path = "./fuso-core"}
fuso-socks = {path ="./fuso-socks"}