[package]
name = "fuso"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
panic = 'abort'
debug = false
rpath = true
split-debuginfo = '...'

[workspace]
members = [
    "./fuso-api",
    "./fuso-core"
]

[[bin]]
name = "fus"
path = "src/server.rs"

[[bin]]
name = "fuc"
path = "src/client.rs"

[[bin]]
name = "no-log-fuc"
path = "src/no-log-client.rs"

[dependencies]
clap = "3.0.0-beta.5"
log = {version = "0.4.14"}
env_logger = "0.9.0"
fuso-core = {path = "./fuso-core"}
smol = {version = "1.2.5"}